Cleaned up compile and emulate scripts so that they would work better for an end user.

diff --git a/simulator/compile b/simulator/compile
--- a/simulator/compile
+++ b/simulator/compile
@@ -1,10 +1,11 @@
 #!/bin/bash
 
-#stop on error, unset variables or pipe failures. 
-set -euo pipefail
-
+rm binary/flash/flash.hex
 echo "Tidy up..."
 rm -f build/*
+
+#stop on error, unset variables or pipe failures. 
+set -euo pipefail
 
 #-------------------------------------------------------------------
 #FIRST WE USE GFORTH TO COMPILE THE NUCLEUS
@@ -21,12 +22,11 @@ rm cross.fs instructionset.fs nucleus.fs nucleuslib.fs
 
 cp build/nucleus.hex build/iceimage.hex
 
-#echo "Creating Flash"
+echo "Creating Flash"
 #This converts the program into a version to be stored in Flash. 
-#cd binary/flash
-#rm flash.hex
-#python3 flash.py
-#cd ../..
+cd binary/flash
+python3 flash.py
+cd ../..
 
 #-------------------------------------------------------------------
 #AND NOW USE THE VERILATOR SIMULATOR TO COMPILE THE REST OF THE CODE
@@ -46,7 +46,7 @@ cat libforth/coredefinitions.fs  \
 cat libforth/insight.fs >> build/included.fs
 
 #This line is for building the boot script.  You should ignore it. 
-cat  forth/forward.fs forth/start.fs forth/process.fs  >> build/included.fs
+#cat  forth/forward.fs forth/start.fs forth/process.fs  >> build/included.fs
 
 osStr=$(uname)
 cpuStr=$(uname -m)
